
winPosHorVert : "+3500+800"
winSizeHorVert : "320x200"
mainFrameCol : '#c62402'
timeLineCol : "green"
timeLineWidth : "2"


breadth : 'f'
position : 'unknown'
week : 'Oct_3'
computer : 'w'   # Post message to screen if configuration file could not be found
