


winPosHorVert : +1500+500 # horizontal and vertical position of main window on the screen
winSizeHorVert : 400x200 # default size of main window
mainFrameCol : '#7E850C' # Colour of the main frame (large frame) of the window
timeLineCol: "green" # Colour of timeline vertical running on screen of schedule
timeLineWidth : '2' # width of timeline in pixels on screen
pixelsPerMinute : 1.0
eightAMline : 700

breadth: 'f' # breadth of coverage for screenshots; 'f' = full week
position: 'LA' # position, LA or p
week: 'Oct_2' # Week of the month, eg: first week of Jan = Jan_1
computer: 'h' # computer program is run on, h = home, w = work, this impacts where files will be saved after screen shots are taken
