


winPosHorVert : +1500+800 # horizontal and vertical position of main window on the screen
winSizeHorVert : 400x200 # default size of main window
mainFrameCol : '#7E850C' # Colour of the main frame (large frame) of the window
timeLineCol: "green" # Colour of timeline vertical running on screen of schedule
timeLineWidth : '2 ' # width of timeline in pixels on screen
